# Generated by Django 4.2 on 2025-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compatible_with',
            field=models.ManyToManyField(blank=True, help_text='Совместимые комплектующие', to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='component_type',
            field=models.CharField(choices=[('cpu', 'Процессор'), ('gpu', 'Видеокарта'), ('ram', 'Оперативная память'), ('motherboard', 'Материнская плата'), ('case', 'Корпус'), ('psu', 'Блок питания'), ('storage', 'Накопитель'), ('other', 'Другое')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='3D модель в формате .glb или .obj', null=True, upload_to='3d_models/'),
        ),
    ]
