# Generated by Django 4.2 on 2025-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_componentoption_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentoption',
            name='type',
            field=models.CharField(choices=[('cpu', 'Процессор'), ('gpu', 'Видеокарта'), ('ram', 'Оперативная память'), ('motherboard', 'Материнская плата'), ('case', 'Корпус'), ('psu', 'Блок питания'), ('storage', 'Накопитель'), ('other', 'Другое')], default='other', help_text='Тип комплектующего', max_length=50),
        ),
    ]
