# Generated by Django 4.2 on 2025-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_componentoption_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Ожидает обработки'), ('Shipped', 'Отправлен'), ('Delivered', 'Доставлен'), ('Cancelled', 'Отменён')], default='Pending', max_length=20),
        ),
    ]
