# Generated by Django 4.2 on 2025-03-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='componentoption',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
